### PR TITLE
Add sorting by number of new weekly followers

### PR DESCRIPTION
**Pull request by baloncek2662**

### CODE REVIEW

**Comment by baloncek2662** [comment]
Also added number of new followers in account card
Screenshot from 2024-07-19 15-17-10

Could also add a new tab next to conferences to show a list allowing to sort by day, week, month

**Review by anze3db — CHANGES_REQUESTED** [review]
Crap, sorting by new followers makes the accounts query 100x slower :(

Before:
Screenshot 2024-07-19 at 18 28 47
After:
Screenshot 2024-07-19 at 18 29 43

This makes sense since the query now needs to go through every account and perform the subquery before it can sort the results. I think it should be a bit faster if we do an outer join instead by removing the annotate and using `"weeklyaccountchange__followers_count"` as the sort. Can you make this change?

**Comment by anze3db** [comment]
The outer join is also not really fast enough. I'm going to try to change the AccountLookup model and make it so that it contains all the data that we sort and filter on.

**Comment by baloncek2662** [comment]
I think I checked all different combinations and everything works fine...
"Order by Last Date" having a filter for "Last day/7 days/...") doesn't make sense, but I didn't think of a good solution for that right now

**Review by anze3db — APPROVED** [review]
Awesome looks great. I just added a few more edge cases and fixed removed the period dropdown for last post date order:

Screenshot 2024-07-23 at 16 37 29

**Pull request merged**
