### PR TITLE
Show stats for most popular languages and frameworks 

### PR DESCRIPTION
**Pull request by baloncek2662**

### CODE REVIEW

**Comment by baloncek2662** [comment]
just now noticed that there is already a similar grid in the Conferences tab but never saw it because my conferences table is empty :see_no_evil: so the stats page can be fixed later if I have time

**Comment by anze3db** [comment]
Awesome, thanks! The statistics page currently isn't showing any data that isn't already visible in the stats page. It would be cool to see which langs/frameworks are trending up and which ones down, you should be able to get this data from the stats_daily table.

We could also draw graphs for each language/framework in the last 30 days. It would look really cool if we had cards for each language that sort of look like this:

Screenshot 2024-08-17 at 16 21 11

Of course instead of visitors we would show number of devs, and then the % could be based on the change from the last 30 days.

**Comment by baloncek2662** [comment]
image

Possible improvements:
- implementing stats for last 7/30/x days should be really easy but the dropdown from https://flowbite.com/docs/plugins/charts/#area-chart stopped working when I placed it in my grid :thinking: 
- I couldn't get the Apex (library for graphs) install with npm working so we are using CDN
- the spacing between columns in full screen mode is maybe unnecessary but couldn't find a fix at first glance

**Comment by baloncek2662** [comment]
fixed 1st and 3rd bullet point from previous comment

**Comment by anze3db** [comment]
Awesome, this looks great! I made some minor tweaks, but all good! 

This should close #18

**Pull request merged**
